name = "Jushido_Brown"
avatar = "images/Wolf.png" # Avatar image. Default to "images/Wolf.png".
bio = "Web developer, edible enjoyer, and fighting game player. "
#company = "Company"
location = "The Mud"

# alternatives:
# location = "<a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>"
# location = "<a href='https://www.google.com/maps/search/Earth'>Earth</a>"
# about = "https://domain.tld" # The external about page. The internal about page will be used if not set.


[params]
  #layout = "compact"
