email = "Mashard30@gmail.com"
github = "SGravesOpen"
twitter = "Jushido_Brown"
#kaggle = "yourkaggleusername"
youtube = "UC12PAv25gdVUMXlFVZN_DMg"
discord = "https://discord.gg/MPCrA4HtCP"
mastodon = "Jushido_Brown"

